### ISSUE TITLE
vendor bundle not updated correctly

### ISSUE THREAD

**Issue by dalimian** [scinos/webpack-plugin-hash-output#10]
I had an issue where one of the bundles was not updated correctly

name of my vendor file was not updated - it was still vendor.bundle.<oldhash>.js - and it pointed to a non-existent source-map file.

this problem occurs only in presence of https://github.com/soundcloud/chunk-manifest-webpack-plugin

I fixed your plugin to be more robust and work with the other plugin, if you are ok, i can submit a pull request - https://www.screencast.com/t/c5sfjhWfiyR

**Comment by scinos** [comment]
Can't reproduce this problem because `chunk-manifest-webpack-plugin` doesn't work with Webpack 4 (https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/55)
