### ISSUE TITLE
Output hash must add the hash in the `emit` compiler hook for webpack 3.

### ISSUE THREAD

**Issue by pksjce** [scinos/webpack-plugin-hash-output#22]
Version - 1.3.0

Currently, the outputhash creates and adds hash to a chunk in the compilation's `after-optimize-assets` hook. After discussion IRL, it seems like this is too early and the outputhash is better off adding the md5 hash at the `emit` lifecycle hook.

**Comment by scinos** [comment]
Solved in 1.3.1 and 3.1.1
